<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDT-Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f1294587-1521-4acf-9248-ccdd233e6db9</testSuiteGuid>
   <testCaseLink>
      <guid>79c4fa7f-38f7-4779-899c-f3cfed204d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DDT/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9fbba5ae-e30b-4748-85cd-8437641b82e9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/datagesyak</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d3510b-a8f0-4a99-8d54-aa917bdc0fdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143fd94d-e98d-423b-8604-24e71a044e06</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
