CREATE DATABASE company;

CREATE TABLE Employee(
SSN CHAR(9) NOT NULL,
FName VARCHAR(15) NOT NULL,
MName CHAR,
LName VARCHAR(15) NOT NULL,
BDate DATE,
Address VARCHAR(30),
Sex CHAR,
Salary DECIMAL(10,2),
SuperSSN CHAR(9),
DNum INT NOT NULL,
CONSTRAINT Employee_SSN_PK PRIMARY KEY(SSN),
CONSTRAINT Employee_SuperSSN_FK FOREIGN KEY(SuperSSN) REFERENCES Employee(SSN) ON DELETE CASCADE);


CREATE TABLE Department(
DNumber INT NOT NULL,
DName VARCHAR(15) NOT NULL,
MgrSSN CHAR(9) NOT NULL,
MgrStartDate DATE,
CONSTRAINT Dept_DNumber_PK PRIMARY KEY(DNumber),
CONSTRAINT Dept_DName_Unique UNIQUE(DName),
CONSTRAINT Dept_MgrSSN_FK FOREIGN KEY(MgrSSN) REFERENCES Employee(SSN) ON DELETE CASCADE);

CREATE TABLE Dept_Locations(
DNum INT NOT NULL,
DLocation VARCHAR(15) NOT NULL,
CONSTRAINT DNumber_DLocation_PF PRIMARY KEY(DNum,DLocation),
CONSTRAINT DLoc_DNum_FK FOREIGN KEY(DNum) REFERENCES
Department(DNumber));

CREATE TABLE Project(
PNumber INT NOT NULL,
PName VARCHAR(15) NOT NULL,
PLocation VARCHAR(15),
DNum INT NOT NULL,
CONSTRAINT Project_PNumber_PK PRIMARY KEY(PNumber),
CONSTRAINT Project_PName_Unique UNIQUE(PName),
CONSTRAINT Project_DNum_FK FOREIGN KEY(DNum)REFERENCES Department(DNumber) ON DELETE CASCADE);

CREATE TABLE Works_On(
ESSN CHAR(9) NOT NULL,
PNum INT NOT NULL,
Hours DECIMAL(3,1) NOT NULL,
CONSTRAINT Works_ESSN_PNum_PK PRIMARY KEY(ESSN,PNum),
CONSTRAINT Works_ESSN_FK FOREIGN KEY(ESSN) REFERENCES Employee(SSN) ON DELETE CASCADE,
CONSTRAINT Works_PNum_FK FOREIGN KEY(PNum) REFERENCES Project(PNumber) ON DELETE CASCADE);

CREATE TABLE Dependent(
ESSN CHAR(9) NOT NULL,
Dependent_Name VARCHAR(15) NOT NULL,
Sex CHAR,
BDate DATE,
Relationship VARCHAR(8),
CONSTRAINT Dependent_ESSN_DepName_PK PRIMARY KEY(ESSN,Dependent_Name),
CONSTRAINT Dependent_ESSN_FK FOREIGN KEY(ESSN) REFERENCES
Employee(SSN));